// @ts-nocheck


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async searchMedias(params: SearchInput) : Promise<Result<SearchOutput | null, { message: string; code: Code }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_medias", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async userPreferences() : Promise<Result<PreferencesOutput | null, { message: string; code: Code }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("user_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateUserPreferences(params: UpdatePreferencesInput) : Promise<Result<UpdatePreferencesMutation | null, { message: string; code: Code }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_user_preferences", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async media(params: MediaInput) : Promise<Result<MediaOutput | null, { message: string; code: Code }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("media", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async providers(params: ProvidersInput) : Promise<Result<ProvidersOutput | null, { message: string; code: Code }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("providers", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setFavoritesProvider(params: SetFavoriteProviderInput) : Promise<Result<SetFavoriteProviderMutation | null, { message: string; code: Code }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_favorites_provider", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setFavoritesMultipleProviders(params: SetFavoriteMultipleProvidersInput) : Promise<Result<SetFavoriteMultipleProvidersMutation | null, { message: string; code: Code }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_favorites_multiple_providers", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMediaReaction(params: SetReactionInput) : Promise<Result<SetReactionMutation | null, { message: string; code: Code }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_media_reaction", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showMainWindow() : Promise<void> {
    await TAURI_INVOKE("show_main_window");
},
async isOnboarded() : Promise<Result<boolean, { message: string; code: Code }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_onboarded") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setOnboarded() : Promise<Result<null, { message: string; code: Code }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_onboarded") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validate() : Promise<Result<null, { message: string; code: Code }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async logout() : Promise<Result<null, { message: string; code: Code }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("logout") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async initializeSessionAuthorization() : Promise<Result<null, { message: string; code: Code }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_session_authorization") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
sessionServerReady: SessionServerReady,
sessionUpdate: SessionUpdate
}>({
sessionServerReady: "session-server-ready",
sessionUpdate: "session-update"
})

/** user-defined constants **/



/** user-defined types **/

export type Availability = { providerId: string; providerName: string; logo: string | null; availableTo: Date | null; urlHash: string; audioLanguages: Language[] | null; subtitleLanguages: Language[] | null; pricesType: WatchPriceType[] | null }
export type Code = "errors.unknown" | "errors.graphql.server" | "errors.database.not_available" | "errors.session.invalid" | "errors.session.keyring" | "errors.events.invalid" | "errors.graphql.no_data"
export type Country = string
export type Date = string
export type DateTime = string
export type ExternalRating = { rating: number; source: RatingSource }
export type Genre = "ACTION" | "ADVENTURE" | "ANIMATION" | "COMEDY" | "CRIME" | "DOCUMENTARY" | "DRAMA" | "FAMILY" | "FANTASY" | "HISTORY" | "HORROR" | "MUSIC" | "MYSTERY" | "ROMANCE" | "SCIENCE_FICTION" | "TV_MOVIE" | "THRILLER" | "WAR" | "WESTERN" | "OTHER"
export type Language = string
export type Media = ({ kind: "MOVIE" } & Movie) | ({ kind: "TVSHOW" } & Tvshow)
export type MediaCharts = { title: string; kind: MediaKind; slug: string; poster: string | null; year: number | null; rank: MediaCountryRanking | null }
export type MediaCountryRanking = { position: number; change: number; points: number; previousPoints: number }
export type MediaInput = { country: Country; slug: string; language?: Language | null }
export type MediaKind = "MOVIE" | "TV_SHOW"
export type MediaOutput = { media: Media | null }
export type MediaSearch = { id: number; slug: string; kind: MediaKind; title: string; overview: string | null; poster: string | null; backdrop: string | null; providers: MeliSearchProvider[]; year: number | null; released: Date | null; updatedAt: DateTime }
export type MediaSearchConnection = { nodes: MediaSearch[]; pageInfo: PageInfo }
export type MediaSimilar = { title: string; overview: string | null; kind: MediaKind; slug: string; poster: string | null; year: number | null }
export type MediaVideo = { source: VideoSource; video_id: string }
export type MeliSearchProvider = { providerId: string; priceTypes: WatchPriceType[] }
export type Movie = { runtime: string; id: number; __typename: string; title: string; slug: string; overview: string | null; tagline: string | null; languages: Language[]; poster: string | null; backdrop: string | null; released: string | null; year: number | null; country: Country | null; tags: Tag[]; trailers: string[]; genres: Genre[]; classification: string | null; countries: Country[]; kind: MediaKind; videos: MediaVideo[]; ratings: ExternalRating[]; ranking: Ranking | null; pochoclinReview: PochoclinReview | null; similars: MediaSimilar[]; similarsFree: MediaSimilar[]; charts: MediaCharts[]; availabilities: Availability[]; talents: People[]; reaction: UserReactionType | null }
export type PageInfo = { endCursor: string | null; hasNextPage: boolean }
export type People = { id: number; rank: number; name: string; role: string | null; roleType: RoleType }
export type PochoclinReview = { review: string; excerpt: string }
export type PreferencesOutput = { preferences: UserPreferences | null }
export type Provider = { key: string; favorite: boolean; name: string; logo: string | null; weight: number | null; priceTypes: WatchPriceType[]; parentKey: string | null }
export type ProvidersInput = { country: Country; query?: string | null }
export type ProvidersOutput = { providers: Provider[] }
export type Ranking = { score: number; position: number; points: number }
export type RatingSource = "IMDB" | "TMDB"
export type RoleType = "EXECUTIVE_PRODUCER" | "DIRECTOR" | "FIRST_ASSISTANT_DIRECTOR" | "SECOND_ASSISTANT_DIRECTOR" | "SECOND_SECOND_ASSISTANT_DIRECTOR" | "SCRIPT_SUPERVISOR" | "PRODUCER" | "WRITER" | "ACTOR"
export type SearchArguments = { collection?: number | null; kind?: MediaKind | null; year?: number | null; providers?: string[] | null; priceTypes?: WatchPriceType[] | null; genres?: Genre[] | null; audio?: Language | null; subtitle?: Language | null; country?: Country | null; withPoster?: boolean | null; featured?: boolean | null }
export type SearchInput = { after?: string | null; arguments?: SearchArguments | null; before?: string | null; country: Country; first?: number | null; language?: Language | null; last?: number | null; query?: string | null; sortKey: SortKey }
export type SearchOutput = { search: MediaSearchConnection }
export type SessionServerReady = { authorization_url: string }
export type SessionUpdate = null
export type SetFavoriteMultipleProvidersInput = { country: Country; providersKey: string[] }
export type SetFavoriteMultipleProvidersMutation = { setFavoriteMultipleProviders: boolean }
export type SetFavoriteProviderInput = { country: Country; providerKey: string; favorite: boolean }
export type SetFavoriteProviderMutation = { setFavoriteProvider: boolean }
export type SetReactionInput = { mediaId: number; reaction: UserReactionType | null }
export type SetReactionMutation = { setReaction: boolean }
export type SortKey = "ID" | "RELEASED_AT" | "CREATED_AT" | "UPDATED_AT" | "POSITION"
export type Tag = string
export type Tvshow = { inProduction: boolean; id: number; __typename: string; title: string; slug: string; overview: string | null; tagline: string | null; languages: Language[]; poster: string | null; backdrop: string | null; released: string | null; year: number | null; country: Country | null; tags: Tag[]; trailers: string[]; genres: Genre[]; classification: string | null; countries: Country[]; kind: MediaKind; videos: MediaVideo[]; ratings: ExternalRating[]; ranking: Ranking | null; pochoclinReview: PochoclinReview | null; similars: MediaSimilar[]; similarsFree: MediaSimilar[]; charts: MediaCharts[]; availabilities: Availability[]; talents: People[]; reaction: UserReactionType | null }
export type UpdatePreferencesInput = { country: Country; language: Language }
export type UpdatePreferencesMutation = { updatePreferences: UserPreferences | null }
export type UserPreferences = { language: Language; country: Country }
export type UserReactionType = "LIKE" | "DISLIKE"
export type VideoSource = "RUMBLE" | "YOUTUBE"
export type WatchPriceType = "RENT" | "BUY" | "FLATRATE" | "FREE" | "CINEMA"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
